name: CD

on:
  push:
    branches: [homolog, prod]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    name: Terraform apply (VPC + EKS + add-ons)
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      TF_ENV: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Configurar credenciais AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
            -backend-config="key=infra-k8s/${TF_ENV}/terraform.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ vars.TF_LOCK_TABLE }}"

      - name: Apply
        run: |
          terraform apply -auto-approve \
            -var="environment=${TF_ENV}" \
            -var="aws_region=${{ vars.AWS_REGION }}" \
            -var="newrelic_license_key=${{ secrets.NEW_RELIC_LICENSE_KEY }}"
